### ISSUE TITLE
Biter attack

### ISSUE THREAD

**Issue by wilderebel** [Pandemoneus/Farlands#3]
Hi,

I got an peacefull setting game with this mod, but the biters just keep attacking.. even if i use console commands to kill the biters and set them on peacefull it doesn't work..

How can i fix this?

**Comment by Pandemoneus** [comment]
If you don't want the modified biter behaviour, I recommend that you disable the mod called Misanthrope. The mod author has stated that it is not a bug that biters attack due to pollution even with peaceful setting on.

You can disable mods in the main menu or by deleting the file called "Misanthrope_0.3.6.zip" in your mod folder.

**Comment by wilderebel** [comment]
Hi Pandemoneus, thanks for the answer.. if i disable the mod i will get an error when i load an game.. the error is "Error while running the on_configuration_changed: **bobtechsave**/control.lua:24 attempt to index field '?' (a nil value)

**Comment by Pandemoneus** [comment]
Oh, that's a bummer. Let me report that bug to Bobingabout.

**Comment by Pandemoneus** [comment]
I tried to reproduce the bug first, but I couldn't. Which version of my modpack are you using?

**Comment by wilderebel** [comment]
euhm, good question.. i'm using 0.1.5 farlands

**Comment by Pandemoneus** [comment]
Try updating to the newest version. Load and then save your map. Then disable Misanthrope.
